# "."命名开头的文件将不会被载入
page: 
    entry: "http://www.mimiip.com/gngao/"
    template: "http://www.mimiip.com/gngao/{page}"
    from: 2
    to: 500
selector:
    iterator: "#middle_wrapper > div > table > tbody > tr"
    ip: "td:nth-child(1)"
    port: "td:nth-child(2)"
    protocal: "td:nth-child(5)"
    proxytype: ""
    filter: ""
category:
    parallelnumber: 3
    delayRange: [3, 5]
    interval: "@every 10s"
debug: true